### ISSUE TITLE
Add more PDE learning Models

### ISSUE THREAD

**Issue by badulion** [badulion/dynabench#39]
- Neural Operators (grid)
- PointTransformer V1, V2, V3 (points)

**Comment by badulion** [comment]
Point Transformer uses data_dict in forward pass - @deepcodin check out what that is

**Comment by deepcodin** [comment]
Point Transformer V1 is implemented and can be used with the dynabench data. There is an example file in examples which can be executed to check functionality. 
Open Questions:
- file structure ok?
- Licensing?
- do we need more documentation in the code?

**Comment by badulion** [comment]
- Renamed model class to PointTransformerV1 from PointTransformerSeg
- Changed module structure to models.point.point_transformer -> will include PointTransformerV2 and PointTransformerV3
- Moved wrapper for iterative rollouts to separate utils module -> can be reused by other iterative models (i.e. PTV2 and PTV3)
